// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package esi

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9e281deaDecodeGithubComAntihaxGoesiEsi(in *jlexer.Lexer, out *GetUniverseBloodlines200OkList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(GetUniverseBloodlines200OkList, 0, 0)
			} else {
				*out = GetUniverseBloodlines200OkList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 GetUniverseBloodlines200Ok
			if in.IsNull() {
				in.Skip()
			} else {
				(v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e281deaEncodeGithubComAntihaxGoesiEsi(out *jwriter.Writer, in GetUniverseBloodlines200OkList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v GetUniverseBloodlines200OkList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e281deaEncodeGithubComAntihaxGoesiEsi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetUniverseBloodlines200OkList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e281deaEncodeGithubComAntihaxGoesiEsi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetUniverseBloodlines200OkList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e281deaDecodeGithubComAntihaxGoesiEsi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetUniverseBloodlines200OkList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e281deaDecodeGithubComAntihaxGoesiEsi(l, v)
}
func easyjson9e281deaDecodeGithubComAntihaxGoesiEsi1(in *jlexer.Lexer, out *GetUniverseBloodlines200Ok) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bloodline_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BloodlineId = int32(in.Int32())
			}
		case "charisma":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Charisma = int32(in.Int32())
			}
		case "corporation_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CorporationId = int32(in.Int32())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "intelligence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Intelligence = int32(in.Int32())
			}
		case "memory":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memory = int32(in.Int32())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "perception":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Perception = int32(in.Int32())
			}
		case "race_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RaceId = int32(in.Int32())
			}
		case "ship_type_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ShipTypeId = int32(in.Int32())
			}
		case "willpower":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Willpower = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e281deaEncodeGithubComAntihaxGoesiEsi1(out *jwriter.Writer, in GetUniverseBloodlines200Ok) {
	out.RawByte('{')
	first := true
	_ = first
	if in.BloodlineId != 0 {
		const prefix string = ",\"bloodline_id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int32(int32(in.BloodlineId))
	}
	if in.Charisma != 0 {
		const prefix string = ",\"charisma\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Charisma))
	}
	if in.CorporationId != 0 {
		const prefix string = ",\"corporation_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.CorporationId))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.Intelligence != 0 {
		const prefix string = ",\"intelligence\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Intelligence))
	}
	if in.Memory != 0 {
		const prefix string = ",\"memory\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Memory))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Perception != 0 {
		const prefix string = ",\"perception\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Perception))
	}
	if in.RaceId != 0 {
		const prefix string = ",\"race_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.RaceId))
	}
	if in.ShipTypeId != 0 {
		const prefix string = ",\"ship_type_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.ShipTypeId))
	}
	if in.Willpower != 0 {
		const prefix string = ",\"willpower\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Willpower))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetUniverseBloodlines200Ok) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e281deaEncodeGithubComAntihaxGoesiEsi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetUniverseBloodlines200Ok) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e281deaEncodeGithubComAntihaxGoesiEsi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetUniverseBloodlines200Ok) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e281deaDecodeGithubComAntihaxGoesiEsi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetUniverseBloodlines200Ok) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e281deaDecodeGithubComAntihaxGoesiEsi1(l, v)
}
